### ISSUE TITLE
Debugging The App

### ISSUE THREAD

**Issue by alirezapaydar** [lujakob/nestjs-realworld-example-app#10]
How can I debug this app?

**Comment by lujakob** [comment]
Sorry, but what do you mean?

**Comment by alirezapaydar** [comment]
> 
> 
> Sorry, but what do you mean? If you want to test it, run as described in the repository description and then use Postman to test the endpoints.

I want to trace some methods. How to config launch.json in vscode?

**Comment by lujakob** [comment]
Sorry, but debugging Node JS apps is not app specific. You can google this.
