### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by futureneo86** [lujakob/nestjs-realworld-example-app#14]
when I Post with authenticate header, code don't run to return function. pls help me
@Injectable()
export class AuthMiddleware implements NestMiddleware {
  constructor(private readonly userService: UserService) {}

  use(): (req: Request, res: Response, next: NextFunction) => void {

    return async (req: Request, res: Response, next: NextFunction) => {
      if (req.headers.authorization && (req.headers.authorization as string).split(' ')[0] === 'Token') {
        const token = (req.headers.authorization as string).split(' ')[1];
        const decoded: any = jwt.verify(token, SECRET);
        const user = await this.userService.findById(decoded.id);

        if (!user) {
          throw new HttpException('User not found.', HttpStatus.UNAUTHORIZED);
        }

        req.user = user.user;
        next();

      } else {
        throw new HttpException('Not authorized.', HttpStatus.UNAUTHORIZED);

      }
    };
  }
}

**Comment by futureneo86** [comment]
Also, it takes long time to run npm start. How to fix it?

**Comment by lujakob** [comment]
@futureneo86 You were right. This was broken. I fixed auth middleware and the authentication header. 
Now you can login in with a user that's in your DB, and GET /api/user
Can you please verify this? 
Thanks for your help!
