### ISSUE TITLE
'aticles' mispelled lead to routes not protected

### ISSUE THREAD

**Issue by rinn7e** [lujakob/nestjs-realworld-example-app#15]
While playing with nestjs realworld, I found out that you can create post without user authenticated due to misspelled `aticles` in `article.module.ts`  https://github.com/lujakob/nestjs-realworld-example-app/blob/master/src/article/article.module.ts#L24-L27

Due to `this.userRepository.findOne(userId)` where userId is null, return the first user instead of throwing an error, it doesn't help detecting that the user does not exist.

I recommend using `this.userRepository.findOne({ where: { id: userId } });`
See this TypeORM issues: https://github.com/typeorm/typeorm/issues/2500

**Comment by lujakob** [comment]
Thanks @rinn7e !! I fixed it.
