### ISSUE TITLE
Transaction management Question

### ISSUE THREAD

**Issue by hiteshjoshi1** [lujakob/nestjs-realworld-example-app#22]
I am trying to understand how to best implement Transaction management in NestJs but no luck so far.
How does transaction rollback happen when you are inserting in multiple tables and one of the insert succeeds and other one fails.
Example in nestjs-realworld-example-app/src/article/article.service.ts

In create(), if this succeeds
```
   const newArticle = await this.articleRepository.save(article);
```
but this fails
```
  await this.userRepository.save(author);
```

**Comment by lujakob** [comment]
This is not about NestJS but about how Typeorm handles transaction. For further info look at the following docs https://github.com/typeorm/typeorm/blob/master/docs/transactions.md
