### ISSUE TITLE
Using sha256 isn't secure for password hashing

### ISSUE THREAD

**Issue by mootrichard** [lujakob/nestjs-realworld-example-app#32]
sha256 is just a message digest, so it really shouldn't be used as an example for password hashing.

You can use argon2 though, which is considered the best current password hashing algorithm.

https://github.com/lujakob/nestjs-realworld-example-app/blob/e471eed02c88dc9bd40f6b4f6ecb55089a1faf7a/src/user/user.entity.ts#L30

```js
const argon2 = require('argon2');
 
try {
  this.password = await argon2.hash("password");
} catch (err) {
  //...
}
```
https://www.npmjs.com/package/argon2

**Comment by lujakob** [comment]
Hey Richard, looks good to me. Thanks for the hint :)
