### ISSUE TITLE
Why is Passport included?

### ISSUE THREAD

**Issue by zachgoll** [lujakob/nestjs-realworld-example-app#36]
Great project here!  Really helping me out as I'm making my first transition from Express to Nest (well, not fully since Nest uses Express).

I see in `package.json` and `auth.middleware.ts` that the Passport library is imported, but do not see it being used anywhere.  Might be worth removing to avoid confusion from those reading through the code?

**Comment by lujakob** [comment]
That's correct. I guess this is a leftover from the early days. I removed it. Thanks for the hint!
