### ISSUE TITLE
Question about the 'RO' naming convention in the entity interfaces

### ISSUE THREAD

**Issue by nfdavenport** [lujakob/nestjs-realworld-example-app#9]
I'm writing my first nestjs app (first node application for that matter) and am using this repo as one way to approach figuring out my best practices, etc.  I was curious what the RO in the various interface objects stood for.

e.g. https://github.com/lujakob/nestjs-realworld-example-app/blob/2b56fb43bb99ad18cef26dcd70882b4e7c83d96d/src/article/article.interface.ts

Is it Return Object or something similar?  I hate following conventions when I don't know what something means and can't explain to someone else!

**Comment by lujakob** [comment]
ResponseObject

**Comment by nfdavenport** [comment]
Thanks!

**Comment by PerminovEugene** [comment]
I got the same question :)

**Comment by werts** [comment]
Aha, interesting
